### ISSUE TITLE
HTML Style does not work

### ISSUE THREAD

**Issue by ustas4** [data-stack-hub/DataStack#35]
```
#  HTML
ds.subheader("HTML")
ds.html("<div style='color:green'>HTML Text</div>")
```

I see black foreground text on white background

**Comment by vishalvora** [comment]
This is expected behavior, any styles found in the html tag is sanitized for security reason and treated as plain text.
This can be by pass with allow_unsafe_html argument(added in version 0.0.10, update DataStack).

```python
from datastack import datastack

ds = datastack(main=True)


#  HTML
ds.subheader("HTML")
ds.html(
    """<div style="color:green">
  HTML text
</div>""",
    allow_unsafe_html=True,
)

```

**Comment by ustas4** [comment]
Arguments: (TypeError("datastack.html() got an unexpected keyword argument 'allow_unsafe_html'"),)

Version updated 0.0.10

**Comment by vishalvora** [comment]
It should work with version 0.0.10, can you make sure the datastack version is updated using ` pip list`.
